### ISSUE TITLE
Esquema/Desenho "encruzilhada"

### ISSUE THREAD

**Issue by jorgesallum** [hedra-editora/bernardo_fascismo#1]
Na página 66 (largepost) "Nesta encruzilhada..." tem que entrar um desenho que consta na primeira edição. 

@paulopompermaier (@jorgesallum em conversa com o autor: consta no arquivo enviado pelo autor, na página 7, "Labirintos (Hedra) 1.2")

**Comment by suzanasalama** [comment]
@jorgesallum @paulopompermaier @felipemusetti ok
